export {default as Liked} from './Liked/index'
export {default as Form} from './Form/index'
export {default as SongList} from './SongList/Songlist'
export {default as BGChange} from './BackgroundChange/BackChange'
export {default as Albumlist} from './Albumlist/index'
export {default as ShowSongs} from './ShowSongs/ShowSongs'
export {default as BandInfo} from './BandInfo/Intro'
