export {default as About} from './About/About'
export {default as Home} from './Home/index'
export {default as Songlist} from './Songlist/index'
export {default as NotFound} from './NotFound/index'
export {default as Albums} from './Albums/index'
export {default as Quiz} from './Quiz/index'
